### ISSUE TITLE
想问一下，为何不把Natasha直接放在NMS组织下？

### ISSUE THREAD

**Issue by tonyqus** [night-moon-studio/NatashaPad#8]
其实如果是单独项目，放哪个组织都一样，但Natasha这个项目似乎有自己的组织，为何不放在NMS下面？我也看了下Natasha的nuget下载量，其实dotnetcore组织对它推广的帮助很小，也不是顶级项目，请问放在那组织下面的好处是什么，求赐教。当然只是我个人的拙见，不知道作者怎么看？

**Comment by WeihanLi** [comment]
应该有一部分原因是历史原因，Natasha 先是在 `dotnetcore` 下，后来才有的 NMS

cc @NMSAzulX (owner of Natasha and NMS)

**Comment by NMSAzulX** [comment]
@tonyqus @WeihanLi  该组织主要是为了构建 Natasha 生态，Natasha 是新时代动态构建的基础库，目前还缺乏完整有价值的实战案例，生态的发展可能会使 Natasha 成为 NCC 的顶级项目。我个人向来看重反馈和实战，至于下载量，是否为顶级项目都不是我关心的。

**Comment by tonyqus** [comment]
听上去有点道理，好的，祝能有效发展。我只是绝的Natasha是个不错的项目，只是和NatashaPad分开，挺奇怪的，建议一起捐给ncc，或者干脆拉回来。

看了代码之后，我知道你和@weihanli都是个技术人，和我一样，不像某些人只吹牛不写代码，整天在造.net神组织和大神，中国.net真的不缺神，正因为神培训机构、神组织太多了，才到了如今这个地步。其实国外社区不造神，因为我们口中的大神都忙着写代码，没空折腾社区。

**Comment by NMSAzulX** [comment]
@tonyqus  我建议瞿总和杨总把NPOI项目的事情协商好，社区是众人的，不要背锅。

**Comment by tonyqus** [comment]
这repo不适合讨论npoi，就不评论了，有兴趣可以去围观下咱们twitter的互怼，墙外的瓜比较香。
